name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  flutter_background_service: ^5.0.5  # Added flutter_background_service dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true
